# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RotateMarkerSymbol
                                 A QGIS plugin
 A plugin that allows the manual rotation of marker symbols for a point layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-28
        copyright            : (C) 2025 by Matt Needle
        email                : matt.needle.nl@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RotateMarkerSymbol class from file RotateMarkerSymbol.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rotate_marker_symbol import RotateMarkerSymbol
    return RotateMarkerSymbol(iface)
