# -*- coding: utf-8 -*-
"""
Rotate Marker Symbol - A QGIS Plugin

A plugin that allows the manual rotation of marker symbols for a point layer.

This plugin provides an interactive map tool that lets users click on point
features and drag to set their rotation angle. The rotation is stored in a
field and applied via data-defined symbol rotation.

Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-28
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Matt Needle
        email                : matt.needle.nl@gmail.com

/***************************************************************************
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 ***************************************************************************/
"""

import os.path

from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject

# Initialize Qt resources from file resources.py
from .resources import *

# Import the refactored worker from core module
from .core.rotate_marker_symbol_worker import PointSymbolRotator

# Import the translation manager
from .core.translation_manager import TranslationManager


class RotateMarkerSymbol:
    """
    QGIS Plugin Implementation for rotating marker symbols.
    
    This plugin adds a map tool to QGIS that allows users to interactively
    rotate point marker symbols. The tool is added to the Vector menu and
    toolbar.
    
    Attributes:
        iface: QGIS interface instance
        plugin_dir: Directory containing the plugin
        translation_manager: Handles plugin translations
        actions: List of QAction objects added by this plugin
        menu: Name of the plugin's menu
        toolbar: The plugin's toolbar (if created)
        first_start: Flag indicating if this is the first run in the session
        point_symbol_rotator: The map tool instance
    """

    def __init__(self, iface):
        """
        Constructor.

        Args:
            iface: An interface instance that will be passed to this class
                which provides the hook by which you can manipulate the QGIS
                application at run time.
        """
        # Save reference to the QGIS interface
        self.iface = iface
        
        # Initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        
        # Initialize translation manager
        self.translation_manager = TranslationManager(
            plugin_name='RotateMarkerSymbol',
            plugin_dir=self.plugin_dir
        )

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Rotate Marker Symbol')

        # Plugin state
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        # Map tool instance
        self.point_symbol_rotator = None

    def tr(self, message):
        """
        Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        Args:
            message: String for translation

        Returns:
            str: Translated version of message
        """
        return self.translation_manager.tr(message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/rotate_marker_symbol/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Rotate Marker Symbol'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """
        Remove the plugin menu item and icon from QGIS GUI.
        
        This is called when the plugin is unloaded. It cleans up all
        UI elements, removes the map tool, and ensures the preview layer
        and all signal connections are properly cleaned up.
        """
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Rotate Marker Symbol'),
                action
            )
            self.iface.removeToolBarIcon(action)

        # Clean up map tool if it exists
        if self.point_symbol_rotator:
            # Ensure complete cleanup including preview layer and signals
            self.point_symbol_rotator.preview_manager.cleanup()
            self.point_symbol_rotator.visual_manager.clear()
        
        # Clean up translation manager
        if self.translation_manager:
            self.translation_manager.unload()

    def run(self):
        """
        Run method that activates the rotation map tool.
        
        This is called when the user clicks the plugin icon or menu item.
        It activates the rotation map tool, allowing the user to interactively
        rotate point features.
        """
        # Mark that we've started at least once
        if self.first_start:
            self.first_start = False

        canvas = self.iface.mapCanvas()

        # Store the instantiated map tool as a class attribute
        # This prevents garbage collection from destroying it before it can run
        self.point_symbol_rotator = PointSymbolRotator(canvas, self.iface)
        canvas.setMapTool(self.point_symbol_rotator)